title: Praveen Kushwaha
logo: /assets/img/praveen_photograph.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/praveenkushwahamech/">LinkedIn</a> |
  <a href="https://github.com/praveenkkushwaha">GitHub</a>
  
  <br>   
  Data Science Enthusiast.
  <br>
  </p>



theme: jekyll-theme-minimal
